### ISSUE TITLE
个人资料恢复系统时出错

### ISSUE THREAD

**Issue by fcl1892** [mobazha/mobazha#4]
当用个人资料恢复系统时，系统有可能强制退出，也有可能恢复的不完整（看不到别人的社交圈，自己也无法发布铁帖子，个人头像消失等现象），
![8fc940c88f589bde329d3cb54afe389](https://user-images.githubusercontent.com/44824168/221398787-3a79235c-612e-4dbe-b387-70e18696e8b7.jpg)

**Comment by fengzie** [comment]
Not reproducible in the recent builds. Close.
